version: '3.8'

services:

  # Gateway service.
  gateway:
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
      target: gateway
    hostname: gateway
    networks:
      - mallard

  # Reverse-proxy service. This should be the only service with
  # publicly-exposed ports.
  proxy:
    image: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./config/local/nginx:/etc/nginx
    networks:
      - mallard

networks:
  # Internal network
  mallard:
