# Example config file for MALLARD. The real config file is located in
# `~/.config/mallard/config.yaml`.

backends:
  # Configuration for the object store backend.
  object_store:
    type: mallard.gateway.backends.objects.s3_object_store.S3ObjectStore
    config:
      region_name: us-east-1
      access_key: minioadmin
      access_key_id: minioadmin
      endpoint_url: http://127.0.0.1:9000

  # Configuration for the metadata store backend.
  metadata_store:
    type: mallard.gateway.backends.metadata.sql.SqlImageMetadataStore
    config:
      endpoint_url: "cockroachdb://root@localhost:26257/mallard_meta?sslmode=disable"

# URL endpoint we use for authentication.
auth_url: https://example.com/auth/
